const ErrorFlags = {
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    URI_NOT_FOUND: 'URI_NOT_FOUND',
    INVALID_BODY: 'INVALID_BODY',
    INVALID_HEADER: 'INVALID_HEADER',
    INVALID_QUERY_PARAM: 'INVALID_QUERY_PARAM',
    INVALID_URL_PARAM: 'INVALID_URL_PARAM',
    SOCKET_CONNECTION_NOT_FOUND: 'SOCKET_CONNECTION_NOT_FOUND',
    CONNECTION_NOT_FOUND: 'CONNECTION_NOT_FOUND',
    NOT_ADMIN: 'NOT_ADMIN'
}

export default ErrorFlags;